[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[sources]
StructArrays = {path = ".."}

[compat]
Documenter = "1"
PooledArrays = "1"
StaticArrays = "1"
